### ISSUE TITLE
ExtrinsicStatus:: 1010: Invalid Transaction: Payment

### ISSUE THREAD

**Issue by danielimkk** [hicommonwealth/edgeware-cli#37]
Hello. I've been trying to stake using edgeware-cli. It seems everything should be ok, but when you try to stake or transfer some amount of EDG it returns an error:
Making tx: staking.bond(["5FpusSiSw1n341negr65EfMj98A26JY4ajxEDYdrfhWpCLSs","0.000000000000000020","Staked"]) [ '5FpusSiSw1n341negr65EfMj98A26JY4ajxEDYdrfhWpCLSs', '20', 'Staked' ] 2020-02-19 17:50:26 RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment 2020-02-19 17:50:26 DRR: Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment at errorHandler (/home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:234:26) at /home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:214:9 at processTicksAndRejections (internal/process/task_queues.js:94:5) Failed: Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment at errorHandler (/home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:234:26) at /home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:214:9 at processTicksAndRejections (internal/process/task_queues.js:94:5)

Could you please tell me what could be an issue?

**Comment by drewstone** [comment]
Ah yea, this has been added to the README but I believe your issue is that staking functionality is in terms of EDG units. So you should input how much you want IN TERMS of EDG instead of the base unit type.

Try staking bond 0.2 to get 2x10^17 units.

**Comment by drewstone** [comment]
Let me know if this just adds confusion and I can change it back. I wasn't sure which route I would take on this CLI since it does seem tedious to enter all decimal places when you want to handle balances, though this inconsistency could prove in poor taste.

**Comment by danielimkk** [comment]
Thank you for such a fast response. I've tried your suggestion, it doesn't help. Even if I past smallest amount possible or just 20 (that converts them to 20*10^18 I guess) I got the same issue when I call `session.setKeys`  
`Making tx: session.setKeys(["0x55f83c17ff7caa4da9358a0534e85b2b34130f7543cda2f19ffb305c317020eecb5c40d27458bf9e6aa54b67f2d5487c6e29cf537cba212866c0503bb5168baea0d79d4b02210a2f0e7fc0f1afbbde698112b89f907cd9b54624d591764e8357e016239fbe026fe7d3c4196fe1547aedf022ab02e715f9c28af6f3d5a534b252"])
[
  '0x55f83c17ff7caa4da9358a0534e85b2b34130f7543cda2f19ffb305c317020eecb5c40d27458bf9e6aa54b67f2d5487c6e29cf537cba212866c0503bb5168baea0d79d4b02210a2f0e7fc0f1afbbde698112b89f907cd9b54624d591764e8357e016239fbe026fe7d3c4196fe1547aedf022ab02e715f9c28af6f3d5a534b252',
  '0x'
]
2020-02-19 18:38:51        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment
2020-02-19 18:38:51             DRR: Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment
    at errorHandler (/home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:234:26)
    at /home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:214:9
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
Failed:  Error: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Payment
    at errorHandler (/home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:234:26)
    at /home/daniel/Ankrnetwork/edgeware/cli/edgeware-cli/node_modules/@polkadot/rpc-core/index.js:214:9
    at processTicksAndRejections (internal/process/task_queues.js:94:5)`

**Comment by drewstone** [comment]
Can you tell me if your bond went through? I will look into this now, definitely make sure you have enough balance to send transactions.

**Comment by danielimkk** [comment]
It didn`t. This is the balance of my stash contoller: 0x0000000000000000d02ab486cedc0000 or 15 tEdg, for stash it is 0x000000000000000229b94699ca160000 or 39 tEDG

**Comment by danielimkk** [comment]
If it works for you, could you then please show me an example? Maybe there is something wrong done by me? Or something should be updated?

**Comment by drewstone** [comment]
Yea truthfully, I had deprecated this repo before because we weren't maintaining it and I will be deprecating it again. Until we have the bandwidth to maintain a separate CLI, this will not be intended for actual use.

I recommend using the Commonwealth UI or Polkadot Apps UI with the PolkadotJS extension
